### ISSUE TITLE
Unbind from localhost

### ISSUE THREAD

**Issue by DorwardTech** [tsilen/zoneboard#2]
Could you please unbind the websocket from localhost and get it to call from the redis.conf binding? 

e.g
bind 192.168.1.x instead of 127.0.0.1

Remote viewing of the scoreboard would be amazing via URL.

Current error when viewing remotely:

_index.js:133 & 89

WebSocket connection to 'ws://localhost:40510/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED_

**Comment by tsilen** [comment]
@DorwardTech That should now be fixed in 0.1.9
